name: Lint

on:
  push:
    branches: [develop]
  pull_request:
    branches: [release, develop]

jobs:
  lint:
    name: Lint task
    runs-on: ubuntu-latest

    steps:
      - name: Check out code 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pkg manager (bun)
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: ESlint linting
        run: bun run lint:eslint

      - name: Prettier linting
        run: bun run lint:prettier
